document.writeln("	<footer class=\'mui-bar mui-bar-footer\' style=\'padding: 0;\'>");
document.writeln("		<ul>");
document.writeln("			<li>");
document.writeln("				<a href=\'index.html\'>");
document.writeln("					 <span class=\'mui-icon mui-icon-home\'></span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a href=\'self.html\'>");
document.writeln("					 <span class=\'mui-icon mui-icon-contact\'></span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a href=\'set.html\'>");
document.writeln("					 <span class=\'mui-icon mui-icon-gear\'></span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("		</ul>	");
document.writeln("	</footer>");