document.writeln("<header class=\'mui-bar mui-bar-nav\'>");
document.writeln("			<h2 class='mui-title mui-pull-left' style='text-align:left'>G联盟</h2>");
document.writeln("			<a id=\'menu\' class=\'mui-action-menu mui-icon mui-icon-bars mui-pull-right\' href=\'#topPopover\'></a>");
document.writeln("			");
document.writeln("		</header>");
document.writeln("		<footer class=\'mui-bar mui-bar-footer\'>");
document.writeln("			<a href=\'#bottomPopover\' class=\'mui-btn mui-btn-link mui-pull-right\'>菜单</a>");
document.writeln("		</footer>");
document.writeln("		");
document.writeln("		<!--右上角弹出菜单-->");
document.writeln("		<div id=\'topPopover\' class=\'mui-popover\' style=\'display: none; top: 57px; left: 372px;\'>");
document.writeln("			<div class=\'mui-popover-arrow\' style=\'left:248px\'></div>");
document.writeln("			<div class=\'mui-scroll-wrapper\' data-scroll=\'1\'>");
document.writeln("				<div class=\'mui-scroll\' style=\'transform: translate3d(0px, 0px, 0px) translateZ(0px);\'>");
document.writeln("					<ul class=\'mui-table-view\'>");
document.writeln("						<li class=\'mui-table-view-cell\'>");
document.writeln("							<a href=\'#\'>Item1</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item2</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item3</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item4</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item5</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item6</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item7</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item8</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item9</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item10</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			<div class=\'mui-scrollbar mui-scrollbar-vertical\'><div class=\'mui-scrollbar-indicator\' style=\'transition-duration: 0ms; display: none; height: 8px; transform: translate3d(0px, -8px, 0px) translateZ(0px);\'></div></div></div>");
document.writeln("");
document.writeln("		</div>");
document.writeln("		<div id=\'middlePopover\' class=\'mui-popover\'>");
document.writeln("			<div class=\'mui-popover-arrow\'></div>");
document.writeln("			<div class=\'mui-scroll-wrapper\' data-scroll=\'2\'>");
document.writeln("				<div class=\'mui-scroll\' style=\'transform: translate3d(0px, 0px, 0px) translateZ(0px);\'>");
document.writeln("					<ul class=\'mui-table-view\'>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item1</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item2</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item3</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item4</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item5</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item6</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item7</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item8</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item9</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'mui-table-view-cell\'><a href=\'#\'>Item10</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			<div class=\'mui-scrollbar mui-scrollbar-vertical\'><div class=\'mui-scrollbar-indicator\' style=\'transition-duration: 0ms; display: none; height: 8px; transform: translate3d(0px, -8px, 0px) translateZ(0px);\'></div></div></div>");
document.writeln("");
document.writeln("		</div>");